---
- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: Update the repository databases and upgrade the system packages.
    tags: always
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Archlinux"

- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: Remove some xfce4 package
    tags: removep
    pacman:
      name: mousepad,parole,xfburn,xfce4-xkb-plugin,xfce4-dict,xfce4-mailwatch-plugin,xfce4-notes-plugin,xfce4-taskmanager
      state: absent
    when: ansible_distribtuion == "Archlinux"

  - name: Install additional packages
    tags: installp
    package:
      name:
        - jq
        - curl
        - dmenu
        - binutils
        - usbutils
        - net-tools
        - traceroute
        - zip
        - unzip
        - unrar
        - which
        - mlocate
        - man-db
        - tldr
        - arch-audit
        - bash-completion
        - neofetch
        - asciinema
        - terminus-font
        - nano-syntax-highlighting
        - firefox
      state: latest

- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: Start system services
    tags: enable
    service:
      name: "{{ items }}"
      state: started
      enabled: yes
    with_items:
      - 'iptables'
      - 'sshd'
      - 'fstrim'

  - name: Disable system services
    tags: disable
    service:
      name: avahi-daemon
      state: stopped
      enabled: no

# Checklist to do:
# - Need to enable iptables.service, sshd.service and fstrim.timer
# - Need to disable avahi-daemon.service 
# - Configure iptables for secure firewall
# - Pull all stuff from GitHub repo (bin, config, fonts, wallpaper, bashrc)
#   - Copy all bin into /usr/local/bin
#   - Copy all config into ~/.config
#   - Copy all fonts to /usr/share/fonts and run fc-cache -fv
#   - Copy all wallpaper to ~/Pictures
#   - Put bashrc in ~
